"""added foriegn_key to planet model

Revision ID: 084488fc64aa
Revises: cce60e577e3e
Create Date: 2023-05-08 20:08:13.232460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084488fc64aa'
down_revision = 'cce60e577e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    # ### end Alembic commands ###
