"""empty message

Revision ID: cce60e577e3e
Revises: 8b2c5b59cacc
Create Date: 2023-05-08 19:51:14.498288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce60e577e3e'
down_revision = '8b2c5b59cacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('mass', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon')
    # ### end Alembic commands ###
