"""empty message

Revision ID: d12b70d81f7f
Revises: f6f9b34297e7
Create Date: 2023-05-02 12:53:46.210669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12b70d81f7f'
down_revision = 'f6f9b34297e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moon_of_planet', sa.String(), nullable=True))
    op.drop_column('planet', 'parent_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('parent_planet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'moon_of_planet')
    # ### end Alembic commands ###
